spring:
  application:
    name: Example
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:ExampleApp;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
  mustache:
    check-template-location: false # No templates yet. Don't check/warn.

server:
  port: 9090
  servlet:
    context-path: /
